eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

spring:
  boot:
    admin:
      client:
        url: http://localhost:9411

# Microservices Endpoints Configuration
microservices:
  payment-service:
    base-url: http://payment-service
    endpoints:
      do-payment: /payment/doPayment
      get-payment: /payment/{orderId}
  order-service:
    base-url: http://order-service
    endpoints:
      create-order: /order
      get-order: /order/{id}
  gateway:
    routes:
      order-prefix: /order/**
      payment-prefix: /payment/**
